language: node_js
node_js:
- 7.9.0
script:
- cd frontend
- npm install
- npm run build
- git checkout -b master
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "thomas@novamedia.nyc"
before_deploy:
- git checkout dev
- cd ../
- "./deploy.sh"
deploy:
  provider: heroku
  app: safe-hamlet-16715
  api_key:
    secure: qZWgBlyjU/CERO2rgv6sLtO9sb9AbsMIzKbjZoqlT1Lfg+9RI+dwG5KgBi+VPF2iRGGmYL8nMfsieg/yGTMCQkAX8N9MxQ643qdjpVvn5glQDQI/50TjmYZ6/lL1SLrwKuHZ5Xp4uXN8jf1j1Yx2CYGbssR6bFsLQAJw7g01RjjofRWGN1LK3V7Nmna92k5Nveu4tmDWTSLvqPmnmFGKQPTRkw2WLSW47kagIO5AZbxzYv0g9E+HGUaxn8IByaUc5KL3eOSxeXuMbV/sC2b04KwYHPb8oxM2zWc+WUAbKtFAL+67phy05wPWZSAkvabmhR1PO54dhUWpsesehzu+HVA4/gYaBpbowE6dvbHK4RwgIftcV/mAVPXOnk2BCN2P4OG0JpZk0JxBJf8ajSvyOEr0awclTPKSV/CjTmt0h7F0S+YdzRg+fy9qHaaWMqEkFLBamLQ5eunE5HNQ42G2dD+9Wh88qZvbHhBPQJ+UbndfvhZuCIIJ45Jr12B/UfrAYSAtV/DDBekLL6icMbURB7kdn4mfFzYBXhtLw43JcK1k5MiqOy1mreLa/mSIz5sATqR3It/GAT2HO8D7CIAKwAVCDnqD3iYKtB3FuJt4x3OwiLtn94FNDTPW3+EkccA84TVk8YIEIvnMmEn1P83GASjWdKzcL8iI55Us2uqGyBM=
  on:
    all_branches: true
