language: node_js
node_js:
- 7.9.0
script:
- cd frontend
- npm install
- npm run build
- git checkout -b master
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "thomas@novamedia.nyc"
before_deploy:
- git checkout dev
- cd ../
- ./deploy.sh
deploy:
  provider: heroku
  app: nova-xr-media
  api_key:
    secure: haAKLK9DEbtT/epo5zI+KrRN8PJ4OlIFJ1V4JP8EHKsZ0VMBt0e/rbnVd86N14ChlwvV9aZIAoNMPhKic+eC9Zy3okwG7kjc6P3z+96mVblY3nYPpxv4qYUOiYKmuoB2NJ7TfBP/13PIC8ry6aOVCSKFnHXWegnSBEDmwUtBX9JAGFQe5P3uAhvGORKC+uO1uH4RaEveZ6RTX8me8M5RZqFin4Bl1MY5mWaaR1FfR6DT5lNBDAfAPcYS1RlnYE+1Eyq7Qd3AcH5MRYeTyaO/uhDwtEGBILe08rdkcnWcKDTCPi9ayW1cBkIfVORMUAIM75tHHHuzTT1hQ0kr2CWI+nE9nxo+N2S2KRwOfZ3ivUAdMFnJdcgzmg+ZoNc0YT+4SJB2Q+yII0e1cQbPsifSq/T79WiY8gKt796EHK7Yr0lm+8jyYubN1AVhfKKFHkE5Yw/YwbPdaDzxpsqF0jOkpbq/Kllcz15erQ6nJEJTmHte7gvdiO756/zRxP63IxGR59ED+KMnChrp4jjbT/LYIc4qJk+5NwTxgUAf+P0oNbvYJDldfEeK7WC9PPseJA+z+heniswUIMIK9IyMBSQH/mL+TCO/1M1xFeHcStp67lrFh/SpA/kMrQs8FsaVSnJyRDkBZM5zMC9Q3jTSRao7UlJ5boCA/v1KdBrIiuNXTHQ=
  on:
    all_branches: true