#!/bin/bash

project_root=code/nova-website
ip=$(ip -o -4 addr list wlp2s0 | awk '{print $4}' | cut -d/ -f1)
export DEBUG=0

source ~/$project_root/venv/bin/activate
python ~/$project_root/manage.py runserver $ip:3001
