import React from "react";
import ReactHtmlParser, {
  processNodes,
  convertNodeToElement,
  htmlparser2,
} from "react-html-parser";

export const proposal = `<div id="content">
<h1 class="title">Doctor Kelly</h1>
<div class="nova-definitions">
  <div class="definition-block">
    <p class="word">
      Extended Reality (XR): <span class="pronounciation">/ikˈstendəd// adjective, rēˈalədē/ noun (/eks/ /är/ nouns)</span>
    </p>

    <p class="definition">
    A term referring to all real and virtual combined environments and human-machine interactions
    generated by computer technology and wearables. It includes representative forms such
    as augmented reality (AR), augmented virtuality (AV) and virtual reality (VR) and the areas
    interpolated among them.
    </p>
  </div>

  <div class="definition-block">
    <p class="word">
    Media: <span class="pronounciation">/ˈmēdēə/ noun</span>
    </p>

    <p class="definition">
    The main means of mass communication (broadcasting, publishing, and the Internet), regarded
    collectively.
    </p>
  </div>
</div>

<div class="nova-logo-page">
  <img src="./print/nova-logo.png" alt="nova-logo" />
</div>

<div class="client-logo-page">
</div>

<div class="intro-page">
</div>
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#org3b60837">Introduction</a></li>
<li><a href="#orgf4a987b">Executive Summary</a></li>
<li><a href="#orgf1e6405">VR Market Analysis</a>
<ul>
<li><a href="#orgfc40aff">XR headset sales</a></li>
<li><a href="#org324c99c">Technology adoption</a></li>
<li><a href="#org2394a43">How VR works</a></li>
</ul>
</li>
<li><a href="#org1af2d52">Execution</a>
<ul>
<li><a href="#orge908d02">Objective</a></li>
<li><a href="#org583b2d6">Strategy</a></li>
</ul>
</li>
<li><a href="#org17412b4">Gantt Chart</a></li>
<li><a href="#org5aa13cc">Production</a>
<ul>
<li><a href="#org7f9f0d2">Tech Architecture</a></li>
<li><a href="#org9d3088c">Production Pipeline</a></li>
<li><a href="#org38af93a">Phases 2</a></li>
<li><a href="#org6dd014d">Phases 3</a></li>
</ul>
</li>
<li><a href="#org35303af">Financial Strategy</a>
<ul>
<li><a href="#orgce6f1f9">Phase 1</a></li>
<li><a href="#org3060f4b">Phase 2</a></li>
<li><a href="#org053f15c">Phase 3</a></li>
</ul>
</li>
<li><a href="#orgae73732">Summary and Net Invest</a></li>
</ul>
</div>
</div>

<div class="page-break">
</div>


<div id="outline-container-org3b60837" class="outline-2">
<h2 id="org3b60837">Introduction</h2>
<div class="outline-text-2" id="text-org3b60837">
<p>
This document is to propose a virtual reality marketing solution for Dr. James Kelly's Vision Correction practices in New York. This program has been developed by Nova Media LLC, led by Joe Mecca, and presented to Dr. James Kelly and Clarisa Estrada. All subject matter enclosed is confidential. The approval of Nova Media LLC must be obtained before this document is shared with any additional parties. 
</p>

<p>
Nova Media is an XR (extended reality) studio and innvoation lab in Red Hook, Brooklyn. We develop XR solutions for businesses by providing access to advanced technologies, sourcing development, and advising on related markets. For more about us, please visit <a href="https://novamedia.nyc">https://novamedia.nyc</a> [<a href="#novamedia">6</a>].
</p>
</div>
</div>

<div id="outline-container-orgf4a987b" class="outline-2">
<h2 id="orgf4a987b">Executive Summary</h2>
<div class="outline-text-2" id="text-orgf4a987b">
<p>
(supposing he investins $100,000 into virtual reality)
</p>

<p>
This program will deliver a VR-based marketing strategy that will earn Kelly Vision a return of $20,000 in profit by 2020. In the process, Dr. Kelly will gain working knowledge of this advanced technology and further his reputation as a pioneer in the field of optometry.
</p>

<p>
This program will progress in four phases. First, we create customized content to appear in Dr. Kelly's office.  Next, we create and distribute customized (2D) content to educate viewers on how VR can reveal a patient's need for an optometrical procedure. Third, we formulate a program to qualify candidates for LASIK through VR. Finally, we license the intellectual property and market it to other doctors in the same field.
</p>
</div>
</div>

<div id="outline-container-orgf1e6405" class="outline-2">
<h2 id="orgf1e6405">VR Market Analysis</h2>
<div class="outline-text-2" id="text-orgf1e6405">
<p>
Greenlight Insights - among the top resources for Virtual Reality market maps, forecasts, and consumer insights - tells us that VR is a $7 billion industry in 2017. More than 60% of that revenue comes from hardware sales, as both industry-leading hardware companies (Facebook and HTC Vive) released new VR headmounts this year. As expected, the pricepoint of installing this young technology in the home is out of reach for most consumers. 
</p>

<p>
As a result - similar to the way our grandparents visited the movie theatre to see films, sporting events, and news updates - millenials are discovering VR at location based entertainmet (LBE) centers across major ciites in the US. One LBE in Lower Manhattan told us they're showing VR to 1,000 unique visitors monthly. 
</p>

<p>
Now that the hardware has established itself in the market, consumers are becoming more literate with VR and will be prepared to use it at home when the pricepoint comes down. As this process unfolds, Greenlight Inisghts forecasts that VR will become a $75 billion industry by 2021, exponentially expanding upon the 10 million homes that already own VR hardware. The future of Dr. Kelly's first-of-its kind content could extend beyond his office and into the hands of millions of Americans who will own the hardware necessary to access it.
</p>
</div>

<div id="outline-container-orgfc40aff" class="outline-3">
<h3 id="orgfc40aff">XR headset sales</h3>
<div class="outline-text-3" id="text-orgfc40aff">

<div class="figure">
<p><img src="./tech-adoption-rate.png" alt="tech-adoption-rate.png" />
</p>
<p><span class="figure-number">Figure 1: </span>Source: The Economist [<a href="#headsetSales">3</a>]</p>
</div>
</div>
</div>

<div id="outline-container-org324c99c" class="outline-3">
<h3 id="org324c99c">Technology adoption</h3>
<div class="outline-text-3" id="text-org324c99c">

<div class="figure">
<p><img src="./headset-sales.png" alt="headset-sales.png" />
</p>
<p><span class="figure-number">Figure 2: </span>Source: Piper Jeffray estimates [<a href="#techAdoption">4</a>]</p>
</div>
</div>
</div>

<div id="outline-container-org2394a43" class="outline-3">
<h3 id="org2394a43">How VR works</h3>
<div class="outline-text-3" id="text-org2394a43">
<p>
Consider the way light is refracted when passing through the cornea, pupil, and lens before being sent through the optic nerve. Well, VR headsets are created with thick glasses that have a more intricate progression of light refraction. The many layers manipulate the light before it reaches the cornea. Along the way, VR systems “hijack” the senses, leading us to believe we're in an artificial world.
</p>


<div class="figure">
<p><img src="./brainonvr-1.png" alt="brainonvr-1.png" />
</p>
<p><span class="figure-number">Figure 3: </span>Source: Univesity of Illinois [<a href="#brain">7</a>]</p>
</div>


<p>
VR systems "hijack" each sense by replacing the natural stimulation with artificial stimulation that is provided by hardware called a display. Using a computer, a virtual world generator maintains a coherent, virtual world. Appropriate "views" of this virtual world are rendered to the display.
</p>
</div>
</div>
</div>


<div id="outline-container-org1af2d52" class="outline-2">
<h2 id="org1af2d52">Execution</h2>
<div class="outline-text-2" id="text-org1af2d52">
</div><div id="outline-container-orge908d02" class="outline-3">
<h3 id="orge908d02">Objective</h3>
<div class="outline-text-3" id="text-orge908d02">
<p>
Increase eye procedures and the average margin per procedure 
</p>
</div>
</div>

<div id="outline-container-org583b2d6" class="outline-3">
<h3 id="org583b2d6">Strategy</h3>
<div class="outline-text-3" id="text-org583b2d6">
<p>
Design customized Virtual Reality content to display in both the waiting room in Dr. Kelly's office and on the two most common VR apps on the market. The content content will serve two related purposes: 
</p>
<ol class="org-ol">
<li>Educate the viewer on the anatomy of the eye</li>
<li>Help the viewer understand whether one of Dr. Kelly's procedures will improve their opitcal health</li>
</ol>
</div>

<div id="outline-container-org77dbb36" class="outline-4">
<h4 id="org77dbb36"><b>Phase 1:</b> $30k - Late 2017: (Broadcast in Dr. Kelly's Office)</h4>
<div class="outline-text-4" id="text-org77dbb36">
<ul class="org-ul">
<li>Install top-of-the-line VR equipment at Dr. Kelly's office.</li>
<li>Familiarize Dr. Kelly and partners/employees with the technology during periodic training sessions.</li>
<li>Design customized content to be experienced at Dr. Kelly's office.</li>
<li>Offer experience to patients so they understand the eye's anatomy and the potential circumstances under which they'll benefit from an optical procedure</li>
<li>Track user's attention and tendencies within experience for revising and maximizing next version of content</li>
</ul>

<p>
This will build Kelly Vision Center's working knowledge of VR, further Dr. Kelly's reputation as a pioneer in the tech field, and build the foundation for a content series that educates a targeted and interested audience on the anatomy and functionality of the eye. This high-tech education process will help patients understand why they're epxeriencing vision complications and how Dr. Kelly's practice can help improve both their vision and the health of their eyes. 
</p>
</div>
</div>

<div id="outline-container-org0a4f55e" class="outline-4">
<h4 id="org0a4f55e"><b>Phase 2</b> $30k - early 2018 (Broadcast on VR apps worldwide)</h4>
<div class="outline-text-4" id="text-org0a4f55e">
<ul class="org-ul">
<li>Configure content to be released on app store</li>
<li>Upload Dr. Kelly's program to Steam and Oculus stores.</li>
<li>Build Social Media marketing strategy that will distribute to an audiene both interested in VR and a candidate for Dr. Kelly's services.</li>
<li>Track the patient's engagement, comments, and attitude towards the VR content</li>
<li>Follow up with interested users and off them a consultation</li>
</ul>

<p>
This content will brand Dr. Kelly as a leader in both optometry and advanced technology.
</p>

<p>
"71 percent of [people] feel that VR makes brands seem "forward-thinking and modern." However, there's even better news for brands' bottom lines: 53 percent of respondents said they'd be more likely to purchase from a brand that uses VR than from one that doesn't." - <a href="http://www.adweek.com/digital/new-study-says-people-are-more-likely-buy-brands-use-virtual-reality-172557/">AdWeek</a> [<a href="#adWeek">9</a>]</p>
</div>
</div>

<div id="outline-container-org3558c60" class="outline-4">
<h4 id="org3558c60"><b>Phase 3 $30-50k</b>  late 2018</h4>
<div class="outline-text-4" id="text-org3558c60">
<ul class="org-ul">
<li>Understand results of first two phases and convert learnings into a more advanced strategy.</li>
<li>design first draft of VR candidate qualification</li>
<li>own IP and license and prepare to distribute to other doctor's offices</li>
</ul>

<p>
As virtual reality grows and creates a major shift in the media landscape, Dr. Kelly will establish himself as one of the early VR content creators in optometry, earning the right to license his content and distribute it to later adopters. 
</p>

<p>
As Dr. Kelly's Vision Correction expands into VR content creation, it brings to mind the story of Amadeus Computer Reservation Systems (one of the first global distribution systems of the late 1980s). Originally founded by a group of airlines, Amadeus was dedicated to increasing airline reservations by connecting pasenger name recognition with travel agencies. After successfully serving that branch of the market, Amadeus expanded into information technologies (today known as "IT") to deliver serves beyond sales and reservations and their business evolved into a new market, allowing it to be on the forefront of the IT industry. Amadeus continues to thrive to this day, <a href="http://www.amadeus.com/web/amadeus/en_1A-corporate/Amadeus-Home/Newsroom/Archive/2017-02-24_Amadeus-Financial-Results-Q4-FY-2016/1319658626891-Page-AMAD_DetailPpal?assetid=1319703282553&amp;assettype=PressRelease_C">profitting close to a billion US Dollars in 2016</a> [<a href="#amadeus">1</a>].
</p>

<div class="page-break">
</div>
</div>
</div>
</div>
</div>
<div id="outline-container-org17412b4" class="outline-2">
<h2 id="org17412b4">Gantt Chart</h2>
<div class="outline-text-2" id="text-org17412b4">
<div class="org-src-container">
<pre class="src src-gantt">- Phase 1 ==&gt; [week 0, week 16]
  - Sign agreement (30k) ==&gt; week 0
  - Install VR hardware ==&gt; day 7
  - user experience spec ==&gt; week 4
  - First demo ==&gt; week 8
  - Second demo ==&gt; week 12
  - Final product in waiting room ==&gt; week 16
- Phase 2 ==&gt; [week 16, week 32]
  - Sign agreement (30k) ==&gt; week 0
  - user experience spec ==&gt; week 20
  - First demo ==&gt; week 24
  - Second demo ==&gt; week 28
  - Final product in app stores ==&gt; week 32
- Phase 3 ==&gt; [week 32, week 48]
  - Sign agreement (30k - 50k) ==&gt; week 32
- Training ==&gt; [week 1, week 32]
</pre>
</div>



<div class="gantt-page-left">
  <img src="./gantt.png" alt="gantt-right" />
</div>

<div class="gantt-page-right">
  <img src="./gantt.png" alt="gantt-right" />
</div>
</div>
</div>


<div id="outline-container-org5aa13cc" class="outline-2">
<h2 id="org5aa13cc">Production</h2>
<div class="outline-text-2" id="text-org5aa13cc">
</div><div id="outline-container-org7f9f0d2" class="outline-3">
<h3 id="org7f9f0d2">Tech Architecture</h3>
<div class="outline-text-3" id="text-org7f9f0d2">
</div><div id="outline-container-orge908261" class="outline-4">
<h4 id="orge908261">Phase 1</h4>
<div class="outline-text-4" id="text-orge908261">
<p>
The application required for the creation of this content will be built in Unity (the platform on which many of the best VR apps are built). After the construction of this 3D content, you will have the option to distribute it on one of the major VR app stores. Launching it in one of these app stores is all that's needed for the content to be available to VR users across the globe. 
</p>
</div>
</div>

<div id="outline-container-orga880369" class="outline-4">
<h4 id="orga880369">Phases 2 and 3</h4>
<div class="outline-text-4" id="text-orga880369">
<p>
Technically speaking, phases 2 and 3 are concerned with the distribution of a Unity 3D VR executable. This can be achieved by making the application available on VR app stores or on a website using the <b>WebGL</b> browser APIs. A website being much more complex to setup, the scope of this proposal is limited to distributing this experience over traditional channels (VR play stores such as Steam or Occulus).
</p>
</div>
</div>
</div>

<div id="outline-container-org9d3088c" class="outline-3">
<h3 id="org9d3088c">Production Pipeline</h3>
<div class="outline-text-3" id="text-org9d3088c">
<p>
2 weeks of pre-production:
</p>

<p>
Develop: 3 weeks
</p>

<p>
Refine: 2 weeks to user test and make fixes.
</p>

<p>
Cost: 10K ($200/week to produce) for interactive Oculus VR Lasik
</p>
</div>


<div id="outline-container-org0efc555" class="outline-4">
<h4 id="org0efc555">Deliverables</h4>
<div class="outline-text-4" id="text-org0efc555">
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<caption class="t-above"><span class="table-number">Table 1:</span> Phase 1 deliverables</caption>

<colgroup>
<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">Week</th>
<th scope="col" class="org-left">Deliverable</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-right">0</td>
<td class="org-left">Confirmation of first payment</td>
</tr>

<tr>
<td class="org-right">4</td>
<td class="org-left">User experience spec</td>
</tr>

<tr>
<td class="org-right">8</td>
<td class="org-left">First demo</td>
</tr>

<tr>
<td class="org-right">12</td>
<td class="org-left">Second demo</td>
</tr>

<tr>
<td class="org-right">16</td>
<td class="org-left">Final product installed in waiting room</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>

<div id="outline-container-org38af93a" class="outline-3">
<h3 id="org38af93a">Phases 2</h3>
<div class="outline-text-3" id="text-org38af93a">
<p>
Technically, phase 2 is centered on the distribution of 3D content developed in Unity. This can be achieved by making the application available on VR app stores or on a website using the <b>WebGL</b> browser APIs. A website being much more complex to setup, the scope of this proposal is limited to distributing this experience over traditional channels (VR play stores such as Steam or Occulus).
</p>
</div>

<div id="outline-container-org649afa3" class="outline-4">
<h4 id="org649afa3">Deliverables</h4>
<div class="outline-text-4" id="text-org649afa3">
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<caption class="t-above"><span class="table-number">Table 2:</span> Phase 2 deliverables</caption>

<colgroup>
<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">Week</th>
<th scope="col" class="org-left">Deliverable</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-right">0</td>
<td class="org-left">Confirmation of first payment</td>
</tr>

<tr>
<td class="org-right">4</td>
<td class="org-left">User experience spec</td>
</tr>

<tr>
<td class="org-right">8</td>
<td class="org-left">First demo</td>
</tr>

<tr>
<td class="org-right">12</td>
<td class="org-left">Second demo</td>
</tr>

<tr>
<td class="org-right">16</td>
<td class="org-left">Final product available in VR stores and user manual</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>

<div id="outline-container-org6dd014d" class="outline-3">
<h3 id="org6dd014d">Phases 3</h3>
<div class="outline-text-3" id="text-org6dd014d">
<p>
The technical architecture of phase 3 will directly depend on what direction the program expansion takes. As the first two phases unfold we will be monitoring their performance and then - together with Dr. Kelly's office - determine how to procede with phase three. As a result, the technical architecture of phase 3 has not yet materialized. Regardless of who phase three develops, we could setup of servers and databases to capture user data and better understand the benefits of phases 1 and 2,  
</p>

<p>
Moreover, building on the data gathered from phases 1 and 2, it becomes possible to serve patients in new ways. One option is to pre-test a prospect's vision using VR headsets, so they can receive a basic diagnosis from home. Then provide recommendations on which surgeries would be most applicable. Additionally, further educational content could be developped to directly increase sales and client satisfaction.
</p>

<p>
After an initial phase of product design to establish phase 3's scope, we will execute the production and provide you with deliverables attesting to the project's advancements every two weeks. These deliverables would include (while not being limited to) design specifications, demos, and user manuals.
</p>
</div>
</div>
</div>

<div id="outline-container-org35303af" class="outline-2">
<h2 id="org35303af">Financial Strategy</h2>
<div class="outline-text-2" id="text-org35303af">
<p>
For phases 1 through 3, we're trying to model the assumption that educating patients increases overall sales <a href="https://www.researchgate.net/publication/280221807_The_Impact_of_Customer_Education_on_Customer_Loyalty_Through_Service_Quality">Suh, et al.</a> [<a href="#suh">8</a>]. Phase 1 concentrates on educating patients at the office, in the waiting room. Whereas Phase 2 targets a broader audience by making use of the internet as a distribution channel. Finally phase 3 builds on phases 1 and 2 to generate a greater income.
</p>
</div>

<div id="outline-container-orgce6f1f9" class="outline-3">
<h3 id="orgce6f1f9">Phase 1</h3>
<div class="outline-text-3" id="text-orgce6f1f9">
<p>
<a href="http://www.qscience.com/doi/pdf/10.5339/qproc.2015.elc2014.6">Dale's Cone of Learning</a> [<a href="#qscience">2</a>] shows us that patients trying the experience will retain 90% of the content. With this recollection of their experience, they are more likely to speak with friends and family members about the VR experience at Dr. Kelly's office. Since <a href="https://www.lasik.com/articles/lasik-eye-surgery-everything-you-need-to-know/">about 80% of US adults are eligible for LASIK surgery</a> [<a href="#lasik">5</a>], even if a patient that isn't eligible for LASIK experiencies the VR app, if he/she spreads the information to 2 friends, it is likely that one of those two adults will be a candidate for LASIK. Many of the people who experience VR in Dr. Kelly's waiting room will be experiencing VR for the first time in their lives. When experiencing innovative tech like VR for the first time, the natural reaction is to spread the word. 
</p>
</div>

<div id="outline-container-orgfef992c" class="outline-4">
<h4 id="orgfef992c">Break even analysis</h4>
<div class="outline-text-4" id="text-orgfef992c">
<ul class="org-ul">
<li><b>Investment:</b> $100k</li>
<li><b>LASIK surgery margin:</b> $1500 (both eyes)</li>
<li><b>Number of patients to convert in order to break even:</b> 100,000 / 1500 = 67 patients</li>
<li>Barring any hardware malfunctions, there is no maintenance cost.</li>
</ul>

<p>
Since there are about 50 work weeks in a year, an average of just over one patient per week needs to be converted to LASIK surgery in order to break even within the first year. Let's say Dr. Kelly has 40 patients per week that experience the VR content while sitting in the waiting room. In this case, an average conversion rate of less than 3% is needed to break even within the year (3% of the time, someone trying the VR experience will result in a new LASIK surgery).
</p>

<p>
Potential market reach to also consider: Given how impressive Virtual Reality content will be for the average visitor to Dr. Kelly's waiting room, these visitors are likely to tell several people about their experience, thus strengthening the spread of word of mouth.  
</p>

<p>
Taking these into account, we can assume with pretty good confidence that in practice, <b>the conversion rate of the VR app needed to break even within the year is lower than 3%</b>.
</p>

<p>
It is this conversion rate that is of interest of us. We claim that 1% is achievable considered the research presented in <a href="https://www.researchgate.net/publication/280221807_The_Impact_of_Customer_Education_on_Customer_Loyalty_Through_Service_Quality">Suh, et al.</a> [<a href="#suh">8</a>]:
</p>
<ul class="org-ul">
<li>"In health care services, Gummesson (2000) discussed the positive effects of customer education before surgery"</li>
<li>"McNeal (1978) suggested that companies should consider education as a major competitive strategy [&#x2026;] Companies will realize manu benefits including larger profits"</li>
<li>"[Customer education] provides customers with information that enables them to make complicated and critical decisions, this empowering them and increasing their self-confidence"</li>
<li>"The findings also indicate that customers may feel more comfortable asking questions when they are educated"</li>
</ul>

<p>
That being said, we are not aware of any literature that quantify conversion rate for VR in a waiting room through rigurous surveying methodology.
</p>

<p>
With 1% conversion rate and 40 patients trying out the VR experience in the office we get the following revenue timeline:
</p>

<table id="org48b9700" border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<caption class="t-above"><span class="table-number">Table 3:</span> Model hypothesis</caption>

<colgroup>
<col  class="org-left" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Constants</th>
<th scope="col" class="org-right">Values</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">conversion rate</td>
<td class="org-right">0.01</td>
</tr>

<tr>
<td class="org-left">margin per client (usd)</td>
<td class="org-right">1500</td>
</tr>

<tr>
<td class="org-left">initial investment (usd)</td>
<td class="org-right">30000</td>
</tr>

<tr>
<td class="org-left">patients tyring vr per week</td>
<td class="org-right">40</td>
</tr>
</tbody>
</table>

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">
<caption class="t-above"><span class="table-number">Table 4:</span> Phase 1 break even analysis</caption>

<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">Quarter</th>
<th scope="col" class="org-right">VR users</th>
<th scope="col" class="org-right">New patients</th>
<th scope="col" class="org-right">Revenue</th>
<th scope="col" class="org-right">Cummulative investment</th>
<th scope="col" class="org-right">Profit</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-right">0</td>
<td class="org-right">0</td>
<td class="org-right">0.</td>
<td class="org-right">0.</td>
<td class="org-right">30000</td>
<td class="org-right">-30000.</td>
</tr>

<tr>
<td class="org-right">1</td>
<td class="org-right">520</td>
<td class="org-right">5.2</td>
<td class="org-right">7800.</td>
<td class="org-right">30000</td>
<td class="org-right">-22200.</td>
</tr>

<tr>
<td class="org-right">2</td>
<td class="org-right">1040</td>
<td class="org-right">10.4</td>
<td class="org-right">15600.</td>
<td class="org-right">30000</td>
<td class="org-right">-14400.</td>
</tr>

<tr>
<td class="org-right">3</td>
<td class="org-right">1560</td>
<td class="org-right">15.6</td>
<td class="org-right">23400.</td>
<td class="org-right">30000</td>
<td class="org-right">-6600.</td>
</tr>

<tr>
<td class="org-right">4</td>
<td class="org-right">2080</td>
<td class="org-right">20.8</td>
<td class="org-right">31200.</td>
<td class="org-right">30000</td>
<td class="org-right">1200.</td>
</tr>

<tr>
<td class="org-right">5</td>
<td class="org-right">2600</td>
<td class="org-right">26.</td>
<td class="org-right">39000.</td>
<td class="org-right">30000</td>
<td class="org-right">9000.</td>
</tr>

<tr>
<td class="org-right">6</td>
<td class="org-right">3120</td>
<td class="org-right">31.2</td>
<td class="org-right">46800.</td>
<td class="org-right">30000</td>
<td class="org-right">16800.</td>
</tr>

<tr>
<td class="org-right">7</td>
<td class="org-right">3640</td>
<td class="org-right">36.4</td>
<td class="org-right">54600.</td>
<td class="org-right">30000</td>
<td class="org-right">24600.</td>
</tr>

<tr>
<td class="org-right">9</td>
<td class="org-right">4680</td>
<td class="org-right">46.8</td>
<td class="org-right">70200.</td>
<td class="org-right">30000</td>
<td class="org-right">40200.</td>
</tr>
</tbody>
</table>


<div id="orgc7ec8f4" class="figure">
<p><img src="break-even-phase-1.png" alt="break-even-phase-1.png" />
</p>
<p><span class="figure-number">Figure 4: </span>Break even analysis for phase 1</p>
</div>
</div>
</div>
</div>

<div id="outline-container-org3060f4b" class="outline-3">
<h3 id="org3060f4b">Phase 2</h3>
<div class="outline-text-3" id="text-org3060f4b">
<p>
Show how much money is made by sharing the experience over the internet:
</p>
<ul class="org-ul">
<li>How many people first try it and how (word to mouth? social media? &#x2026;)</li>
<li>How many people tell their friends about the experience ? Solve the differential equation modeling shares of the experience with peers</li>
<li>What's the conversion rate from VR 'experiencer' to LASIK patient?</li>
</ul>
<p>
===&gt; calc benefits over time and infer break even point
</p>
</div>
</div>

<div id="outline-container-org053f15c" class="outline-3">
<h3 id="org053f15c">Phase 3</h3>
<div class="outline-text-3" id="text-org053f15c">
<p>
Phase 3 has for goal to increase the conversion rates from the VR experiences implemented in phases 1 and 2 (i.e. both the applications in the office and on the internet).
</p>
</div>
</div>
</div>

<div id="outline-container-orgae73732" class="outline-2">
<h2 id="orgae73732">Summary and Net Invest</h2>
<div class="outline-text-2" id="text-orgae73732">
<p>
This program will put Kelly Vision at the forefront of innovative media and yeild a <span class="underline"><span class="underline"><span class="underline"><span class="underline"><span class="underline"><span class="underline"><span class="underline">_</span></span></span></span></span></span></span> Retun on Investment . XR is going to (market information and growth)_______ By developing simple XR content, Kelly will build a reputation for being the optomotrist who knows the most about this complex medium that is becoming all the craze, and increase both his number of surgeries and the amount he can charge per procedure.
</p>


<div id="bibliography">
<h2>References</h2>

<table>

<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="amadeus">1</a>]
</td>
<td class="bibtexitem">
Amadeus.
 Quaterly report 2016.
[&nbsp;<a href="http://www.amadeus.com/web/amadeus/en_1A-corporate/Amadeus-Home/Newsroom/Archive/2017-02-24_Amadeus-Financial-Results-Q4-FY-2016/1319658626891-Page-AMAD_DetailPpal?assetid=1319703282553&amp;assettype=PressRelease_C">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="qscience">2</a>]
</td>
<td class="bibtexitem">
Summers&nbsp;Michele Davis&nbsp;Beverly.
 The Impact of Customer Education on Customer Loyalty Through Service
  Quality.
[&nbsp;<a href="http://www.qscience.com/doi/pdf/10.5339/qproc.2015.elc2014.6">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="headsetSales">3</a>]
</td>
<td class="bibtexitem">
The Economist.
 XR Headset Sales.
[&nbsp;<a href="https://economist.com">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="techAdoption">4</a>]
</td>
<td class="bibtexitem">
Piper Jeffray.
 XR adoption rate.
[&nbsp;<a href="https://economist.com">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="lasik">5</a>]
</td>
<td class="bibtexitem">
Lasik.com.
 Everything You Need to Know about LASIK Eye Surgery.
[&nbsp;<a href="https://www.lasik.com/articles/lasik-eye-surgery-everything-you-need-to-know/">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="novamedia">6</a>]
</td>
<td class="bibtexitem">
Nova Media.
 Nova Media Website.
[&nbsp;<a href="https://www.novamedia.nyc">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="brain">7</a>]
</td>
<td class="bibtexitem">
University of&nbsp;Illinois.
 Unkown.
[&nbsp;<a href="https://www.uoi.edu/">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="suh">8</a>]
</td>
<td class="bibtexitem">
Munshik Suh, Greene Henry, Israilov Israilov, and Rho Taeseok.
 The Impact of Customer Education on Customer Loyalty Through Service
  Quality.
[&nbsp;<a href="https://www.researchgate.net/publication/280221807_The_Impact_of_Customer_Education_on_Customer_Loyalty_Through_Service_Quality">http</a>&nbsp;]

</td>
</tr>


<tr valign="top">
<td align="right" class="bibtexnumber">
[<a name="adWeek">9</a>]
</td>
<td class="bibtexitem">
Ad&nbsp;Week.
 Branding through VR.
[&nbsp;<a href="http://www.adweek.com/digital/new-study-says-people-are-more-likely-buy-brands-use-virtual-reality-172557/">http</a>&nbsp;]

</td>
</tr>
</table>
</div>


<div class="business-cards-page">
</div>

<div class="business-cards-page">
  <img src="./print/joey-business-card.png" alt="Joey Mecca contact info" />
</div>

<div class="white-page">
</div>

<div class="white-page">
</div>

<div class="final-page">
</div>
</div>
</div>
</div>
<div id="postamble" class="status">
<p class="date">Date: November 2017</p>
<p class="author">Author: Nova Media</p>
<p class="date">Created: 2017-11-13 Mon 04:58</p>
<p class="validation"><a href="http://validator.w3.org/check?uri=referer">Validate</a></p>
</div>`;

export default class HtmlComponent extends React.Component {
  render() {
    const html = proposal;
    console.log(proposal);

    return <div>{ReactHtmlParser(html)}</div>;
  }
}
