import * as React from 'react'

import { connect } from 'react-redux'

import { styles as appStyles } from '../../constants.js'

import {
    P,
    BigText,
    FlexColumn,
} from './UI.jsx'

const mapStateToProps = function(state) {
    return {
        windowWidth: state.appReducer.windowWidth,
    }
}

const mapDispatchToProps = function(dispatch) {
    return {
    }
}

/**
   HOME PAGE
**/

const HomePage = props => {
    const styles = {
        wrapper:{
            position: 'relative',
            fontSize: appStyles.UI.P.fontSize,
        },
        word: {
            fontWeight: 'bold',
        },
        mobile: {
            display: props.windowWidth < appStyles.mediaQueries.phone ? 'block' : 'none',
        },
    }

    return (
        <div
            className={ 'HomePage--wrapper' }
            style={ styles.wrapper }>
            <FlexColumn>
                <P style={ styles.mobile }>
                    We provide XR Media solutions for business. Our work includes sourcing development, production management, and market entry.
                </P>
                <P><span style={ styles.word }>(XR) Extended Reality</span> refers to all real-and-virtual combined environments and human-machine interactions generated by computer technology and wearables. It includes representative forms such as :</P>
            </FlexColumn>
            <ul>
                <li>Augmented Reality (AR)</li>
                <li>Augmented Virtuality (AV)</li>
                <li>Virtual Reality (VR)</li>
            </ul>
        </div>
    )
}

HomePage.defaultProps = {
}

const ConnectedHomePage = connect(
    mapStateToProps,
    mapDispatchToProps
)(HomePage)

export default ConnectedHomePage
