# Generated by Django 2.1.1 on 2018-11-01 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildXR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Submission date')),
            ],
            options={
                'verbose_name': 'BuildXR answer',
                'verbose_name_plural': 'BuildXR answers',
            },
        ),
        migrations.CreateModel(
            name='BusinessProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='publication date')),
                ('picto', models.ImageField(upload_to='business_props_pdfs')),
                ('content', markdownx.models.MarkdownxField()),
                ('password', models.CharField(default='', max_length=100)),
                ('exec_sum', markdownx.models.MarkdownxField()),
                ('bg_image', models.ImageField(upload_to='business_props_bgs')),
                ('pdf', models.FileField(blank=True, upload_to='business_props_pdfs')),
                ('storage', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Business Proposition',
                'verbose_name_plural': 'Business Propositions',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='imgs')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='products_pics')),
                ('pictoBg', models.ImageField(upload_to='products_pics')),
                ('squarePicto', models.ImageField(upload_to='products_pics')),
                ('content', markdownx.models.MarkdownxField()),
                ('abstract', markdownx.models.MarkdownxField()),
                ('bg_image', models.ImageField(upload_to='products_bgs')),
                ('pdf', models.FileField(blank=True, upload_to='business_props_pdfs')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('introduction', markdownx.models.MarkdownxField()),
                ('content_text', markdownx.models.MarkdownxField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novaAPI.Section')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novaAPI.Subsection'),
        ),
    ]
