# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 13:55
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='myfield',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
