# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0003_auto_20180311_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='partnership_productions_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Deploy',
                'verbose_name_plural': 'Deploy',
            },
        ),
    ]
