# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 20:57
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0003_blogpost_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='myfield',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
