# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0004_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='careers_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='partners_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='productions_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
            },
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='picto',
            field=models.ImageField(upload_to='about_us_pics'),
        ),
        migrations.AlterField(
            model_name='community',
            name='picto',
            field=models.ImageField(upload_to='community_pics'),
        ),
        migrations.AlterField(
            model_name='crossindustry',
            name='picto',
            field=models.ImageField(upload_to='cross_industry_pics'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='picto',
            field=models.ImageField(upload_to='deploy_pics'),
        ),
        migrations.AlterField(
            model_name='design',
            name='picto',
            field=models.ImageField(upload_to='design_pics'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='picto',
            field=models.ImageField(upload_to='industry_pics'),
        ),
        migrations.AlterField(
            model_name='learninglab',
            name='picto',
            field=models.ImageField(upload_to='learning_lab_pics'),
        ),
        migrations.AlterField(
            model_name='network',
            name='picto',
            field=models.ImageField(upload_to='network_pics'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='picto',
            field=models.ImageField(upload_to='produce_pics'),
        ),
        migrations.AlterField(
            model_name='program',
            name='picto',
            field=models.ImageField(upload_to='program_pics'),
        ),
    ]
