# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 01:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novaAPI', '0004_auto_20180123_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='consultancy_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='partnership_productions_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='products_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='publication_pics')),
                ('pdf', models.FileField(upload_to='publication_pdfs')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='publishing_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('picto', models.ImageField(upload_to='solutions_production_pics')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='picto',
            field=models.ImageField(default='', upload_to='blog_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessproposition',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessproposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='publication date'),
        ),
        migrations.AddField(
            model_name='businessproposition',
            name='pdf',
            field=models.FileField(default='', upload_to='publication_pdfs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessproposition',
            name='picto',
            field=models.ImageField(default='', upload_to='publication_pics'),
            preserve_default=False,
        ),
    ]
