# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0005_auto_20180311_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='about_us_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='blog_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='careers_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='community_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossindustry',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='cross_industry_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploy',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='deploy_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='design_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='industry_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learninglab',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='learning_lab_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='network_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='partners_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produce',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='produce_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pictoBg',
            field=models.ImageField(default='', upload_to='products_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='products_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='productions_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='program_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='squarePicto',
            field=models.ImageField(default='', upload_to='publication_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
