# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0006_auto_20180209_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
