# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0006_auto_20180324_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='career',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='community',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='crossindustry',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='design',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='learninglab',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='network',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='production',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='program',
            name='squarePicto',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='squarePicto',
        ),
    ]
