# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0007_auto_20180324_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposition',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
