# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0008_businessproposition_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='abstract',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='bg_image',
            field=models.ImageField(default='', upload_to='products_bgs'),
            preserve_default=False,
        ),
    ]
