# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0009_auto_20180606_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='bg_image',
        ),
    ]
