# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0011_auto_20180606_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessproposition',
            old_name='abstract',
            new_name='exec_sum',
        ),
    ]
