# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-11 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaAPI', '0013_businessproposition_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildXR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Submission date')),
            ],
            options={
                'verbose_name': 'BuildXR answer',
                'verbose_name_plural': 'BuildXR answers',
            },
        ),
    ]
